# Generated by Django 4.2.24 on 2026-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order_ref',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
